services:
  - type: web
    name: women-safety-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MAIL_USERNAME
        value: your_email@gmail.com
      - key: MAIL_PASSWORD
        value: your_gmail_app_password
      - key: SECRET_KEY
        value: your_flask_secret_key
